### ISSUE TITLE
The agentdeploy controller cannot update the agent manifestWorks in time when the cluster is changed

### ISSUE THREAD

**Issue by zhiweiyin318** [open-cluster-management-io/addon-framework#198]
there are some cases the agent manifestworks have dependancies on the managed cluster, like the annotation or clusterClaim. 
but the agentdeploy controller only watches the addon and manifestwork, does not watch cluster, so cannot update manifestWorks in time when the cluster is changed.

**Comment by zhiweiyin318** [comment]
cc @zhujian7

**Comment by zhujian7** [comment]
It is not a good idea to watch the managed cluster for all addons, since it is easy to change, which may cause some performance issues. So we are going to provide a filter function that developers can use to filter which information the addon is interested in: https://github.com/open-cluster-management-io/addon-framework/pull/199
