### ISSUE TITLE
Installed ManagedClusterAddon not removed after unregistering the ManagedCluster

### ISSUE THREAD

**Issue by yue9944882** [open-cluster-management-io/addon-framework#86]
After deleting a managed cluster from the hub, the cluster namespace still remains and the ManagedClusterAddons under that cluster namespace are also not stripped from the hub cluster. 

I'm not sure if this is the expected behavior, but clarifying the deletion order of these per-cluster resources in the hub data-plane will be helpful.

**Comment by qiujian16** [comment]
/assign @zhiweiyin318 

I think we should create a proposal to define the deletion behavior.

**Comment by qiujian16** [comment]
@zhiweiyin318 is this fixed already?

**Comment by zhiweiyin318** [comment]
@qiujian16 no, the deletion proposal still needs to be revised and there are some details which are unclear.

**Comment by USER0308** [comment]
@zhiweiyin318 Is this fixed already? I am meeting the same problem now. ManagedClusterAddons created by ClusterManagementAddons such as `cluster-proxy`, `cluster-gateway`,`service-account` still exist event if managedCluster has been deleted. And I try to delete these ManagedClusterAddon by hand, it success, but their manifestworks still remain and cannot be deleted, until deleting the manifestworks' finalizer.

**Comment by zhiweiyin318** [comment]
@USER0308 , not yet. we have an enhancement https://github.com/open-cluster-management-io/ocm/issues/140 to follow up the enhancement of mcl deletion process including how to cleanup the addon and manifestwork. 
currently ,suggest deleting addon before deleting managedcluster.  
it will be great if you can add your use cases to that enhancement issue. thanks .

**Comment by USER0308** [comment]
Use case:
Three managedClusters(mcl-1,mcl-2,mcl-3) join into one hub cluster and `cluster-proxy`, `cluster-gateway`, `service-account` these three clusterManagementAddons are installed in hub cluster.

Now I want to detach `mcl-1` from hub cluster.

If I firstly delete managedClusterAddon in mcl-1 namespace, it will be recreated by ClusterManagementAddon and it is not work.

If I firstly delete the ClusterManagementAddon, the managedClusterAddon in all of three managedClusters might be deleted, which against my will.

So, after several try, I find that it is work when firstly deleting the managedCluster mcl-1, then deleting the managedClusterAddons in mcl-1 namespace, which will not be recreated since the managedCluster mcl-1 is already not exist.

But this method still has a shortcoming that manifestworks in mcl-1 namespace are still remain and cannot be deleted until removing their's finalizer.

**Comment by zhiweiyin318** [comment]
https://github.com/open-cluster-management-io/ocm/issues/140 has completed. Now we support to delete addon and manifests after cluster is deleted.
